# -*- coding: utf-8 -*-
"""Lab04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rj7H1MNPIqwcN7xyN7bozqYIo0OiElBR
"""

import os

if not os.path.exists('thinkdsp.py'):
    !wget https://github.com/AllenDowney/ThinkDSP/raw/master/code/thinkdsp.py

import numpy as np
import matplotlib.pyplot as plt
from thinkdsp import read_wave, Spectrum
from thinkdsp import decorate

from thinkdsp import Chirp

signal = Chirp(start=2500, end=3000)
wave1 = signal.make_wave(duration=1, framerate=20000)
wave1.make_audio()
spectrum = wave1.make_spectrum()
spectrum.plot()
decorate(xlabel='Częstotliwość (Hz)', ylabel='Amplituda')

def plot_spectrogram(wave, seg_length):
    """
    """
    spectrogram = wave.make_spectrogram(seg_length)
    print('Rozdzielczość czasowa (s)', spectrogram.time_res)
    print('Rozdzielczość częstotliwościowa (Hz)', spectrogram.freq_res)
    spectrogram.plot(high=700)
    decorate(xlabel='Czas(s)', ylabel='Częstotliwość (Hz)')

wave2 = read_wave("Glissando.wav")
plot_spectrogram(wave2, 2048)

sound = read_wave("Thunder.wav")
sound.make_audio()

segment = sound.segment(duration=0.5)
spectrum1 = segment.make_spectrum()
spectrum1.plot(linewidth=0.5)

sound1 = read_wave("Wind-in-the-forest.wav")
sound1.make_audio()

segment1 = sound1.segment(duration=0.1)
spectrum2 = segment.make_spectrum()
spectrum2.plot(linewidth=0.5)

"""Są to szumy czerwone, zmieniają się w czasie """