# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hffgid2oG15nozEY4mBHtE33qTAwmrYN
"""

import os

if not os.path.exists('thinkdsp.py'):
    !wget https://github.com/AllenDowney/ThinkDSP/raw/master/code/thinkdsp.py

from thinkdsp import SquareSignal
from thinkdsp import decorate
import matplotlib.pyplot as plt
import numpy as np

signal = SquareSignal(1100)
duration = signal.period*5
wave = signal.make_wave(duration, framerate=10000)
wave.plot()
decorate(xlabel='Czas (s)')
wave.make_audio()

from thinkdsp import TriangleSignal
from thinkdsp import decorate

signal = TriangleSignal(440)
fala = signal.make_wave(0.1, framerate=10000)
fala.plot()
decorate(xlabel='Czas (s)')
fala.make_audio()

segment1 = fala.segment(duration=0.005)
segment1.plot()
decorate(xlabel='Czas (s)')

spectrum = fala.make_spectrum()
spectrum.plot()
decorate(xlabel='Częstotliwość (Hz)')
print(spectrum.hs[0])

spectrum.hs[0]=100
fala2 = spectrum.make_wave()
fala2.normalize()
fala2.plot()
fala2.make_audio
decorate(xlabel='Czas (s)')

segment2 = fala2.segment(duration=0.005)
segment2.plot()
decorate(xlabel='Czas (s)')

"""zakres fali spadl"""
